package swt.apis2015.entities;
// Generated 16.06.2015 20:43:58 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Beteiligung generated by hbm2java
 */
@Entity
@Table(name="Beteiligung"
)
public class Beteiligung  implements java.io.Serializable {


     private Long id;
     private Date datum;
     private HealthProfessional healthProfessional;
     private PatPhenomen patPhenomen;

    public Beteiligung() {
    }

    public Beteiligung(Date datum, HealthProfessional healthProfessional, PatPhenomen patPhenomen) {
       this.datum = datum;
       this.healthProfessional = healthProfessional;
       this.patPhenomen = patPhenomen;
    }
   
     @Id @GeneratedValue

    
    @Column(name="id", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="datum")
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    
    @Column(name="healthProfessional")
    public HealthProfessional getHealthProfessional() {
        return this.healthProfessional;
    }
    
    public void setHealthProfessional(HealthProfessional healthProfessional) {
        this.healthProfessional = healthProfessional;
    }

    
    @Column(name="patPhenomen")
    public PatPhenomen getPatPhenomen() {
        return this.patPhenomen;
    }
    
    public void setPatPhenomen(PatPhenomen patPhenomen) {
        this.patPhenomen = patPhenomen;
    }
}