package swt.apis2015.entities;
// Generated 16.06.2015 20:43:58 by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import swt.apis2015.enums.InsurenceContract;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "Patient")
public class Patient extends Person implements java.io.Serializable {

    private InsurenceContract insuranceContract;
    private int patientOID;
    @OneToMany
    private List<Instance> ehrEntry;

    public Patient() {
    }

    public InsurenceContract getInsuranceContract() {
        return this.insuranceContract;
    }

    public void setInsuranceContract(InsurenceContract insuranceContract) {
        this.insuranceContract = insuranceContract;
    }

    public int getPatientOID() {
        return this.patientOID;
    }

    public void setPatientOID(int patientOID) {
        this.patientOID = patientOID;
    }

    public List<Instance> getEhrEntry() {
        return ehrEntry;
    }

    public void setEhrEntry(List<Instance> ehrEntry) {
        this.ehrEntry = ehrEntry;
    }

}
