/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swt.apis2015.gui;

import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.table.DefaultTableModel;
import swt.apis2015.logic.WaitListHandler;
import swt2.apis2015.dto.PatientDto;

/**
 * Dieses Fenster zeigt die Warteliste an
 */
public class WaitListView extends javax.swing.JFrame implements Observer {

    DefaultTableModel dtm;
    WaitListHandler wLh;

    /**
     * Creates new form WaitListView Hier wird die Warteliste aus der logik
     * Schicht geladen die Tabelle bisherige Tabelle gelöscht die Warteliste
     * gesetzt der Warteliste ein Observer hinzugefügt, sich selbst als
     * beobachter
     *
     */
    public WaitListView() {
        initComponents();
        dtm = (DefaultTableModel) resultT.getModel();
        wLh = WaitListHandler.getInstance();
        List<PatientDto> pl = wLh.getWaitList();
        clearTable();

        if (pl.size() > 0) {
            int i = 0;
            for (PatientDto x : pl) {
                dtm.insertRow(i++, new Object[]{x.getSurname(), x.getFirstname(), x.getBirthday().toGMTString(), x.getPostalCode(), x.getCity(), x.getStreet()});
            }
        }
        WaitListHandler.getInstance().addObserver(this);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultT = new javax.swing.JTable();
        addPatButton = new javax.swing.JButton();
        nextPatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onCloseHandler(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jScrollPane2.setBackground(new java.awt.Color(102, 153, 255));

        resultT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nachname", "Vorname", "Geburtstag", "PLZ", "Ort", "Strasse"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(resultT);

        addPatButton.setBackground(new java.awt.Color(102, 102, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("swt/apis2015/internationalisation/WaitListView"); // NOI18N
        addPatButton.setText(bundle.getString("WaitListView.addPatButton.text")); // NOI18N
        addPatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatButtonActionPerformed(evt);
            }
        });

        nextPatButton.setBackground(new java.awt.Color(102, 102, 255));
        nextPatButton.setText(bundle.getString("WaitListView.nextPatButton.text")); // NOI18N
        nextPatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPatButton)
                .addGap(29, 29, 29)
                .addComponent(nextPatButton)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatButton)
                    .addComponent(nextPatButton))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     Hier wird ein fenster zusätzlich geöffnet in dem der Patient erfasst wird
     */
    private void addPatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatButtonActionPerformed
        PatRegistrationView prv = new PatRegistrationView();
        prv.setVisible(true);
    }//GEN-LAST:event_addPatButtonActionPerformed

    /*
     Hier kann der nächste Patient aufgerufen werden 
    wlh.next löscht den nächsten Patienten aus der Warteliste;
     */
    private void nextPatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPatButtonActionPerformed
        this.dispose();
        this.setVisible(false);
        EpaView ew;
        ew = new EpaView(wLh.next().getId());
        ew.setVisible(true);
    }//GEN-LAST:event_nextPatButtonActionPerformed

    private void onCloseHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onCloseHandler
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_onCloseHandler

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextPatButton;
    private javax.swing.JTable resultT;
    // End of variables declaration//GEN-END:variables

    /*
    Hier wird die Tabelle neu gesetzt wenn in der logikschicht sich etwas an der Warteliste ändert  
    */
    @Override
    public void update(Observable o, Object arg) {
        System.out.println("askdnsdfklön");
        List<PatientDto> pl = wLh.getWaitList();

        clearTable();

        if (pl.size() > 0) {
            int i = 0;
            for (PatientDto x : pl) {
                dtm.insertRow(i++, new Object[]{x.getSurname(), x.getFirstname(), x.getBirthday().toGMTString(), x.getPostalCode(), x.getCity(), x.getStreet()});
            }
        }
    }

    private void clearTable() {
        if (dtm.getRowCount() > 0) {
            for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                dtm.removeRow(i);
            }
        }
    }
}
